M48
; DRILL file {KiCad 8.0.6} date 2025-05-30T23:27:35-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-30T23:27:35-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X196.42Y-92.91
X196.42Y-98.69
T2
X181.6Y-90.4
X187.6Y-96.4
M30
